// Code generated by wsdlgen. DO NOT EDIT.

// Package opw
package opw

import (
	"bytes"
	"context"
	"encoding/xml"
	"fmt"
	"io"
	"net/http"
)

type Client struct {
	HTTPClient   *http.Client
	ResponseHook func(*http.Response) *http.Response
	RequestHook  func(*http.Request) *http.Request
}
type soapEnvelope struct {
	XMLName struct{} `xml:"http://schemas.xmlsoap.org/soap/envelope/ Envelope"`
	Header  []byte   `xml:"http://schemas.xmlsoap.org/soap/envelope/ Header"`
	Body    struct {
		Message interface{}
		Fault   *struct {
			String string `xml:"faultstring,omitempty"`
			Code   string `xml:"faultcode,omitempty"`
			Detail string `xml:"detail,omitempty"`
		} `xml:"http://schemas.xmlsoap.org/soap/envelope/ Fault,omitempty"`
	} `xml:"http://schemas.xmlsoap.org/soap/envelope/ Body"`
}

func (c *Client) do(ctx context.Context, method, uri, action string, in, out interface{}) error {
	var body io.Reader
	var envelope soapEnvelope
	if method == "POST" || method == "PUT" {
		var buf bytes.Buffer
		envelope.Body.Message = in
		enc := xml.NewEncoder(&buf)
		if err := enc.Encode(envelope); err != nil {
			return err
		}
		if err := enc.Flush(); err != nil {
			return err
		}
		body = &buf
	}
	req, err := http.NewRequest(method, uri, body)
	if err != nil {
		return err
	}
	req.Header.Set("SOAPAction", action)
	req = req.WithContext(ctx)
	if c.RequestHook != nil {
		req = c.RequestHook(req)
	}
	httpClient := c.HTTPClient
	if httpClient == nil {
		httpClient = http.DefaultClient
	}
	rsp, err := httpClient.Do(req)
	if err != nil {
		return err
	}
	defer rsp.Body.Close()
	if c.ResponseHook != nil {
		rsp = c.ResponseHook(rsp)
	}
	dec := xml.NewDecoder(rsp.Body)
	envelope.Body.Message = out
	if err := dec.Decode(&envelope); err != nil {
		return err
	}
	if envelope.Body.Fault != nil {
		return fmt.Errorf("%s: %s", envelope.Body.Fault.Code, envelope.Body.Fault.String)
	}
	return nil
}
func (c *Client) Execute(ctx context.Context, in0 string) (string, error) {
	var input struct {
		XMLName struct{} `xml:"http://mpayvn.modules.esb.onebill.onepay.com execute"`
		Args    struct {
			In0 string `xml:"http://mpayvn.modules.esb.onebill.onepay.com in0"`
		} `xml:"http://mpayvn.modules.esb.onebill.onepay.com executeRequest"`
	}
	input.Args.In0 = string(in0)
	var output struct {
		XMLName struct{} `xml:"http://mpayvn.modules.esb.onebill.onepay.com execute"`
		Args    struct {
			ExecuteReturn string `xml:"http://mpayvn.modules.esb.onebill.onepay.com executeReturn"`
		} `xml:"http://mpayvn.modules.esb.onebill.onepay.com executeResponse"`
	}
	err := c.do(ctx, "POST", "http://127.0.0.1:60006/mpayvn-ws/services/mPAYvnOnebillWS", "", &input, &output)
	return string(output.Args.ExecuteReturn), err
}
